# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Journalistic Instinct
email: ychristinezhang@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  Knight-Mozilla <a href="https://opennews.org/what/fellowships/info/">OpenNews</a> Fellow at <a href="https://twitter.com/LATdatadesk">L.A. Times</a>, 
  ex-think-tanker at <a href="https://twitter.com/BrookingsGlobal">Brookings</a>, 
  aspiring data journalist at ???
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://underthecurve.github.io" # the base hostname & protocol for your site
twitter_username: christinezhang
github_username:  underthecurve

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM
